apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: xmo-se-tls
spec:
  secretName: xmo-se
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: xmo.se
  dnsNames:
    - xmo.se
    - www.xmo.se
  acme:
    config:
      - http01:
        ingressClass: nginx
      domains:
        - xmo.se
        - www.xmo.se